### ISSUE TITLE
Suggestion: to make ranking more enjoyable, tweak it a little bit by making 4th place +1 and 5th place -1 instead of the current system where 4th and 5th placers get no rank change

### ISSUE THREAD

**Issue by zaldrizes** [custom-ivan/atomic_war#21]
It would make struggling to get top 4 more enjoyable, but also keep it within the zero-sum game system where the output of the entire match is neither positive nor negative

**Comment by Chengjiajuntttttt** [comment]
Sorry, I think this is very unfriendly for novices and players who are not very advanced

**Comment by Chengjiajuntttttt** [comment]
But we will still consider this suggestion, thank you for your suggestion

**Comment by zaldrizes** [comment]
yw, it's just the most common system (teamfight tactics and hearthstone's battlegrounds use this system so every game 'matters' a bit)
